[library]
name = "Songs"
directory = "/home/s1dd/Downloads/temp/" # just an example

[ftp]
username = "client"
salt = "random_salt_value"
password_hash = "0a4dd737a1f7ab1f0b8f36f7ed75959febad3de996b5d5a8779547a7083fff16" # default password is `password`

[debug]
parser_log = "false" # false to disable it, true to enable it

# NOTE: Only `Tab`, `Escape`, `Enter/Return` and `Space` are accepted as special chars aside from [a-Z][0-9] charset
[keybinds]
scroll_up = "h"
scroll_down = "l"
toggle_focus = "Tab" # to toggle between window panes (Songs and Artists)
show_help = "?" # Toggles help window
toggle_play = "Space"
play_song = "Enter"
play_song_next = "n"
play_song_prev = "p"
vol_up = "="
vol_down = "-"
toggle_mute = "m"
quit_app = "q"
seek_ahead_5 = "l"
seek_behind_5 = "h"
view_lyrics = "2" # or 'L' works
goto_main_screen = "1" # main ui
replay_song = "r"
add_song_to_queue = "a"
play_this_song_next = "b"
view_song_queue = "3"
