#
# Example config.toml for the inLimbo project.
# 
# URL: https://github.com/nots1dd/inLimbo 
# Author: Siddharth Karanam (nots1dd)
# 

[library]
name = "Songs"
directory = "/home/s1dd/Downloads/temp/" # just an example

[ftp]
username = "client"
salt = "random_salt_value"
password_hash = "0a4dd737a1f7ab1f0b8f36f7ed75959febad3de996b5d5a8779547a7083fff16" # default password is `password`

[debug]
parser_log = "false" # false to disable it, true to enable it
debounce_time_in_ms = "500" # Adding debounce to events (minimum is 500)

# NOTE: Only `Tab`, `Escape`, `Enter/Return` and `Space` are accepted as special chars aside from:
# [a-zA-Z0-9!@#$%\^&*\(\)<>\?/`~:;'"\[\]{}\|,\.-=+] charset
[keybinds]
scroll_up = "h"
scroll_down = "l"
toggle_focus = "Tab" # to toggle between window panes (Songs and Artists)
show_help = "?" # Toggles help window
toggle_play = "Space"
play_song = "Enter"
play_song_next = "n"
play_song_prev = "p"
vol_up = "="
vol_down = "-"
toggle_mute = "m"
quit_app = "q"
seek_ahead_5 = "l"
seek_behind_5 = "h"
view_lyrics = "2" # or 'L' works
goto_main_screen = "1" # main ui
replay_song = "r"
add_song_to_queue = "a"
add_artists_songs_to_queue = "e"
remove_song_from_queue = "d"
play_this_song_next = "b"
view_song_queue = "3"
view_current_song_info = "i"

# Colors format: Solid Colors and Hexadecimal values of format `#RRGGBB`
[colors]
# Window Border Colors
active_win_border_color = "#D65D0E"       # Orange for active borders
inactive_win_border_color = "#3C3836"     # Dark grey for inactive borders

# Album Section
album_name_bg = "#83A598"                 # Muted cyan for background

# Menu Cursor
menu_cursor_bg = "#8EC07C"                # Soft green for cursor background

# Artists Title Section
artists_title_bg = "#458588"              # Deep teal for background
artists_title_fg = "#EBDBB2"              # Gruvbox light for foreground

# Songs Title Section
songs_title_bg = "#D79921"                # Warm yellow for background
songs_title_fg = "#EBDBB2"                # Gruvbox light for foreground

# Song Queue Menu
song_queue_menu_bor_col = "#B16286"       # Muted magenta for border
song_queue_menu_fg = "#D3869B"            # Soft pink for foreground

# Progress Bar
progress_bar_playing_col = "#83A598"      # Cyan for playing state
progress_bar_not_playing_col = "#FABD2F"  # Bright yellow for not playing state

# Volume Bar
volume_bar_col = "#8EC07C"                # Soft green for volume bar

# Status Bar
status_bar_bg = "#504945"                 # Dark gray for background
status_bar_artist_col = "#FB4934"         # Bright red for artist name
status_bar_song_col = "#FABD2F"           # Bright yellow for song name
