# -----------------------------------------------------------
# Generate PluginList.ipp
# -----------------------------------------------------------
set(PLUGIN_LIST_IPP "${CMAKE_BINARY_DIR}/generated/PluginList.ipp")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated")

set(_PLUGIN_MACROS "")
set(_PLUGIN_STRINGS "")
set(_PLUGIN_COUNT 0)

foreach(name IN LISTS INLIMBO_FRONTEND_NAMES)
    string(TOUPPER "${name}" NAME_UPPER)

    set(_PLUGIN_MACROS
        "${_PLUGIN_MACROS}#define INLIMBO_FRONTEND_${NAME_UPPER} 1\n")

    set(_PLUGIN_STRINGS
        "${_PLUGIN_STRINGS}  \"${name}\",\n")

    math(EXPR _PLUGIN_COUNT "${_PLUGIN_COUNT} + 1")
endforeach()

file(WRITE "${PLUGIN_LIST_IPP}"
"#pragma once

// Auto-generated by CMake — DO NOT EDIT

#define INLIMBO_FRONTEND_COUNT ${_PLUGIN_COUNT}

${_PLUGIN_MACROS}

static constexpr const char* INLIMBO_FRONTEND_NAMES[] = {
${_PLUGIN_STRINGS}
};
")
