execute_process(
  COMMAND git rev-parse HEAD
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_HASH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
  COMMAND git rev-parse --short=8 HEAD
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_HASH_SHORT
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
  COMMAND git rev-parse --abbrev-ref HEAD
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_BRANCH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
  COMMAND git diff --quiet
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  RESULT_VARIABLE GIT_DIRTY_RESULT
)

set(GIT_DIRTY 0)
if(NOT GIT_DIRTY_RESULT EQUAL 0)
  set(GIT_DIRTY 1)
endif()

add_compile_definitions(
  INLIMBO_GIT_COMMIT_HASH="${GIT_HASH}"
  INLIMBO_GIT_COMMIT_SHORT="${GIT_HASH_SHORT}"
  INLIMBO_GIT_BRANCH="${GIT_BRANCH}"
  INLIMBO_GIT_DIRTY=${GIT_DIRTY}
)
